### ISSUE TITLE
Possibly incorrect capture name for the 1st comment in a file.

### ISSUE THREAD

**Issue by alexaandru** [applejag/tree-sitter-risor#1]
First of all, being the 1st issue in the repo, I want to start with a big THANK YOU!! This is really great and already so helpful :-)

As for the bug, given the file:

```
// foo
// bar
// baz
```

I would expect that the query would capture all the three lines as comments. However, the capture name for the 1st comment in a file is "preproc", and the rest of the comments are correctly identified as "comment". I'm still new to Risor, does it even have preprocs at all?

The tree looks correct: `(source_file (comment) (comment) (comment))` so it is only a query related issue.

**Comment by applejag** [comment]
Hello! Thanks for the issue :)

I'm marking the first comment as preproc just to colorize a shebang correctly. But that should only happen with `#!` comments, and only on the first line.

Will fix

**Comment by alexaandru** [comment]
> Hello! Thanks for the issue :)

My pleasure :-)

> I'm marking the first comment as preproc just to colorize a shebang correctly. But that should only happen with `#!` comments, and only on the first line.

Ah, that makes sense...

If I may add: maybe it's a better idea to use a name similar to what other queries use for this capture? Seems like both https://github.com/nvim-treesitter/nvim-treesitter/blob/master/queries/bash/highlights.scm#L228 and https://github.com/nvim-treesitter/nvim-treesitter/blob/master/queries/perl/highlights.scm#L4 use `@keyword.directive` for it. That would make the colorscheme creators' lives a tiny bit easier :-) 
 
> Will fix

**Comment by applejag** [comment]
> If I may add: maybe it's a better idea to use a name similar to what other queries use for this capture? Seems like both https://github.com/nvim-treesitter/nvim-treesitter/blob/master/queries/bash/highlights.scm#L228 and https://github.com/nvim-treesitter/nvim-treesitter/blob/master/queries/perl/highlights.scm#L4 use `@keyword.directive` for it. That would make the colorscheme creators' lives a tiny bit easier :-)

Great tips! I've been cross referencing a lot when creating this, as ***it is my first rodeo*** :p So the more inspiration sources the merrier

**Comment by alexaandru** [comment]
This is quite something for the first rodeo :-) Cheers!

**Comment by alexaandru** [comment]
Looks like my bug report was incorrect: there is nothing wrong with the highligting query itself, the problem is in the Go binding library, i.e. https://github.com/smacker/go-tree-sitter/blob/master/bindings.go#L831-L858 - I don't see any `lua-match?` implemented anywhere in there.

FWIW, although the way you implemented the shebang search is commonly used by other parsers' queries as well, it is also incorrect, see: https://en.wikipedia.org/wiki/Shebang_(Unix), I quote _" The space between #! and interpreter is optional. There could be any number of spaces or tabs either before or after interpreter."_  So you will miss valid shebangs, that include space, i.e. `#!     /usr/bin/risor` wouldn't work, when it should. You should just ditch the `/`.

While we're at it, shebangs can even work on Windows, and can look like `#!"C:\Program Files\Foobar\foo.exe" -whatever` (double quotes are required for paths with spaces). So the safest choice is to stick with `^#!`.

That being said, none of that have anything to do with the current issue, hence I'll close it!

**Comment by alexaandru** [comment]
I think I finally figured it out :-) I was wrong earlier, the Go bindings don't implement `lua-match?` for a good reason - it is not part of official treesitter: https://tree-sitter.github.io/tree-sitter/using-parsers#match-not-match-any-match-any-not-match - but it is an extension that nvim_treesitter uses (and queries designed for it).

So by using it, you are locking yourself only to nvim, however there is nothing that needs lua in your regex, you can simply use `match?` instead which is standard/more general and thus will work everywhere :-)  including neovim but not only.

**Comment by alexaandru** [comment]
Yeah, I can confirm it works as expected when the matcher is changed from `lua-match?` to `match?`:
![good_shebang](https://github.com/user-attachments/assets/a592874f-6f4c-40e2-8685-b2ebffa269ce)
![no_shebang](https://github.com/user-attachments/assets/6ed76088-7ae6-4391-a402-03e6533a0e29)
